// SPDX-FileCopyrightText: 2026 CERN
// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// Modified: 2026-09-25, Kari Vierimaa, Kempele, Finland.
// Translated from VHDL to SystemVerilog.
// Upstream: https://gitlab.com/colibri-cern/colibri commit 3fa784121ccea86d9e65b2e0dc08d2a3327f5f2f

// Generated by PeakRDL-regblock-vhdl; behavior translated from the VHDL.
// The generated `if false` async-reset branch is dead and is omitted.
// `--pragma translate_off` ack asserts are simulation-only and are not SVA.

`timescale 1ns/1ps

module mmap_fifo_csr (
  input  logic        clk,
  input  logic        rst,

  input  logic        s_cpuif_req,
  input  logic        s_cpuif_req_is_wr,
  input  logic [31:0] s_cpuif_addr,
  input  logic [31:0] s_cpuif_wr_data,
  input  logic [31:0] s_cpuif_wr_biten,
  output logic        s_cpuif_req_stall_wr,
  output logic        s_cpuif_req_stall_rd,
  output logic        s_cpuif_rd_ack,
  output logic        s_cpuif_rd_err,
  output logic [31:0] s_cpuif_rd_data,
  output logic        s_cpuif_wr_ack,
  output logic        s_cpuif_wr_err,

  input  mmap_fifo_csr_pkg::mmap_fifo_csr_in_t  hwif_in,
  output mmap_fifo_csr_pkg::mmap_fifo_csr_out_t hwif_out
);

  logic        cpuif_req;
  logic        cpuif_req_is_wr;
  logic [31:0] cpuif_addr;
  logic [31:0] cpuif_wr_data;
  logic [31:0] cpuif_wr_biten;
  logic        cpuif_req_stall_wr;
  logic        cpuif_req_stall_rd;
  logic        cpuif_rd_ack;
  logic        cpuif_rd_err;
  logic [31:0] cpuif_rd_data;
  logic        cpuif_wr_ack;
  logic        cpuif_wr_err;
  logic        cpuif_req_masked;

  logic external_pending;
  logic external_wr_ack;
  logic external_rd_ack;

  typedef struct {
    logic tx;
    logic rx;
  } decoded_reg_strb_t;

  decoded_reg_strb_t decoded_reg_strb;
  logic              decoded_req_is_external;
  logic [31:0]       decoded_addr;
  logic              decoded_req;
  logic              decoded_req_is_wr;
  logic [31:0]       decoded_wr_data;
  logic [31:0]       decoded_wr_biten;

  logic [31:0] rd_mux_addr;
  logic [31:0] pending_rd_addr;
  logic        readback_external_rd_ack_c;
  logic        readback_external_rd_ack;
  logic        readback_err;
  logic        readback_done;
  logic [31:0] readback_data;

  assign cpuif_req         = s_cpuif_req;
  assign cpuif_req_is_wr   = s_cpuif_req_is_wr;
  assign cpuif_addr        = s_cpuif_addr;
  assign cpuif_wr_data     = s_cpuif_wr_data;
  assign cpuif_wr_biten    = s_cpuif_wr_biten;
  assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
  assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
  assign s_cpuif_rd_ack    = cpuif_rd_ack;
  assign s_cpuif_rd_err    = cpuif_rd_err;
  assign s_cpuif_rd_data   = cpuif_rd_data;
  assign s_cpuif_wr_ack    = cpuif_wr_ack;
  assign s_cpuif_wr_err    = cpuif_wr_err;

  // Read and write latencies are balanced. Stalls are required only while
  // an external access is outstanding.
  assign cpuif_req_stall_rd = external_pending;
  assign cpuif_req_stall_wr = external_pending;
  assign cpuif_req_masked   = cpuif_req
    & ~((~cpuif_req_is_wr) & cpuif_req_stall_rd)
    & ~(cpuif_req_is_wr & cpuif_req_stall_wr);

  always_comb begin : proc_decode
    logic tx_hit;
    logic rx_hit;
    tx_hit = reg_utils::to_std_logic(
      // verilator lint_off UNSIGNED
      (reg_utils::regvec#(32)::to_unsigned(cpuif_addr) >= 32'h0)
      && (reg_utils::regvec#(32)::to_unsigned(cpuif_addr) <= 32'h1B));
      // verilator lint_on UNSIGNED
    rx_hit = reg_utils::to_std_logic(
      (reg_utils::regvec#(32)::to_unsigned(cpuif_addr) >= 32'h20)
      && (reg_utils::regvec#(32)::to_unsigned(cpuif_addr) <= 32'h3B));
    decoded_reg_strb.tx    = cpuif_req_masked & tx_hit;
    decoded_reg_strb.rx    = cpuif_req_masked & rx_hit;
    decoded_req_is_external = (cpuif_req_masked & tx_hit) | (cpuif_req_masked & rx_hit);
  end

  always_ff @(posedge clk) begin : proc_external_pending
    if (rst) begin
      external_pending <= 1'b0;
    end else if (decoded_req_is_external && !external_wr_ack && !external_rd_ack) begin
      external_pending <= 1'b1;
    end else if (external_wr_ack || external_rd_ack) begin
      external_pending <= 1'b0;
    end
  end

  assign decoded_addr      = cpuif_addr;
  assign decoded_req       = cpuif_req_masked;
  assign decoded_req_is_wr = cpuif_req_is_wr;
  assign decoded_wr_data   = cpuif_wr_data;
  assign decoded_wr_biten  = cpuif_wr_biten;

  always_comb begin : proc_hwif_out
    hwif_out.tx.req       = decoded_reg_strb.tx;
    hwif_out.tx.addr      = decoded_addr[4:0];
    hwif_out.tx.req_is_wr = decoded_req_is_wr;
    hwif_out.tx.wr_data   = decoded_wr_data;
    hwif_out.tx.wr_biten  = decoded_wr_biten;
    hwif_out.rx.req       = decoded_reg_strb.rx;
    hwif_out.rx.addr      = decoded_addr[4:0];
    hwif_out.rx.req_is_wr = decoded_req_is_wr;
    hwif_out.rx.wr_data   = decoded_wr_data;
    hwif_out.rx.wr_biten  = decoded_wr_biten;
  end

  assign external_wr_ack = hwif_in.tx.wr_ack | hwif_in.rx.wr_ack;
  assign cpuif_wr_ack    = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_req_is_external);
  assign cpuif_wr_err    = 1'b0;

  assign readback_external_rd_ack_c = hwif_in.tx.rd_ack | hwif_in.rx.rd_ack;
  assign readback_external_rd_ack   = readback_external_rd_ack_c;

  always_ff @(posedge clk) begin : proc_pending_rd_addr
    if (rst)
      pending_rd_addr <= '0;
    else if (decoded_req)
      pending_rd_addr <= decoded_addr;
  end

  assign rd_mux_addr = decoded_req ? decoded_addr : pending_rd_addr;

  always_comb begin : proc_readback
    logic [31:0] readback_data_var;
    readback_data_var = '0;
    // verilator lint_off UNSIGNED
    if ((rd_mux_addr >= 32'h0) && (rd_mux_addr <= 32'h1B))
    // verilator lint_on UNSIGNED
      readback_data_var = hwif_in.tx.rd_data;
    if ((rd_mux_addr >= 32'h20) && (rd_mux_addr <= 32'h3B))
      readback_data_var = hwif_in.rx.rd_data;
    readback_data = readback_data_var;
    readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_req_is_external;
    readback_err  = 1'b0;
  end

  assign external_rd_ack = readback_external_rd_ack;
  assign cpuif_rd_ack    = readback_done | readback_external_rd_ack;
  assign cpuif_rd_data   = readback_data;
  assign cpuif_rd_err    = readback_err;

endmodule
