// SPDX-FileCopyrightText: 2026 CERN
// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// Modified: 2026-09-25, Kari Vierimaa, Kempele, Finland.
// Translated from VHDL to SystemVerilog.
// Upstream: https://gitlab.com/colibri-cern/colibri commit 3fa784121ccea86d9e65b2e0dc08d2a3327f5f2f

// Generated by PeakRDL-regblock-vhdl; record layout translated from the VHDL.
// VHDL package `mmap_fifo_csr_pkg` stays `mmap_fifo_csr_pkg` (no name collision).
// Extended identifiers are legal here (no `.` in the type names).

`timescale 1ns/1ps

package mmap_fifo_csr_pkg;

  localparam int unsigned MMAP_FIFO_CSR_DATA_WIDTH = 32;
  localparam int unsigned MMAP_FIFO_CSR_MIN_ADDR_WIDTH = 32;
  localparam int unsigned MMAP_FIFO_CSR_SIZE = 60;

  typedef struct {
    logic        rd_ack;
    logic [31:0] rd_data;
    logic        wr_ack;
  } txfifo_csr__external_in_t;

  typedef struct {
    logic        rd_ack;
    logic [31:0] rd_data;
    logic        wr_ack;
  } rxfifo_csr__external_in_t;

  typedef struct {
    txfifo_csr__external_in_t tx;
    rxfifo_csr__external_in_t rx;
  } mmap_fifo_csr_in_t;

  typedef struct {
    logic        req;
    logic [4:0]  addr;
    logic        req_is_wr;
    logic [31:0] wr_data;
    logic [31:0] wr_biten;
  } txfifo_csr__external_out_t;

  typedef struct {
    logic        req;
    logic [4:0]  addr;
    logic        req_is_wr;
    logic [31:0] wr_data;
    logic [31:0] wr_biten;
  } rxfifo_csr__external_out_t;

  typedef struct {
    txfifo_csr__external_out_t tx;
    rxfifo_csr__external_out_t rx;
  } mmap_fifo_csr_out_t;

endpackage
