// SPDX-FileCopyrightText: 2026 CERN
// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// Modified: 2026-09-25, Kari Vierimaa, Kempele, Finland.
// Translated from VHDL to SystemVerilog.
// Upstream: https://gitlab.com/colibri-cern/colibri commit 3fa784121ccea86d9e65b2e0dc08d2a3327f5f2f

// Convenience types and utility functions used by the autogenerated regblock code.
// VHDL package `reg_utils` stays `reg_utils` (no collision with `colibri_utils`).
//
// VHDL unconstrained arrays (`std_logic_arrayN`, `std_logic_vector_arrayN`) are
// unused by the generated CSR and are not declared: SystemVerilog needs a fixed
// element type.
// `ieee.fixed_pkg` `ufixed`/`sfixed` overloads are unused by the generated CSR
// and have no fixed-point type here.

`timescale 1ns/1ps

package reg_utils;

  function automatic logic bitswap_sl(input logic value);
    return value;
  endfunction

  function automatic logic or_reduce_sl(input logic value);
    return value;
  endfunction

  function automatic logic to_std_logic(input logic value);
    if (value)
      return 1'b1;
    return 1'b0;
  endfunction

  function automatic logic [0:0] to_unsigned_sl(input logic value);
    return value;
  endfunction

  function automatic logic signed [0:0] to_signed_sl(input logic value);
    return signed'(value);
  endfunction

  function automatic logic [0:0] to_std_logic_vector_sl(input logic value);
    return value;
  endfunction

  // Width-dependent overloads of the VHDL functions. W is the vector length.
  class regvec #(parameter int W_REQ = 1);
    localparam int W = (W_REQ < 1) ? 1 : W_REQ;

    static function automatic logic [W-1:0] bitswap(input logic [W-1:0] vec);
      logic [W-1:0] result;
      for (int i = 0; i < W; i++)
        result[i] = vec[(W - 1) - i];
      return result;
    endfunction

    static function automatic logic [W-1:0] to_unsigned(input logic [W-1:0] vec);
      return vec;
    endfunction

    static function automatic logic signed [W-1:0] to_signed(input logic [W-1:0] vec);
      return signed'(vec);
    endfunction

    static function automatic logic [W-1:0] to_std_logic_vector(input logic [W-1:0] vec);
      return vec;
    endfunction

    static function automatic logic [W-1:0] from_std_logic_vector(input logic [W-1:0] vec);
      return vec;
    endfunction

    static function automatic logic or_reduce(input logic [W-1:0] vec);
      return |vec;
    endfunction
  endclass

endpackage
