// SPDX-FileCopyrightText: 2026 CERN
// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// Modified: 2026-09-25, Kari Vierimaa, Kempele, Finland.
// Translated from VHDL to SystemVerilog.
// Upstream: https://gitlab.com/colibri-cern/colibri commit 3fa784121ccea86d9e65b2e0dc08d2a3327f5f2f

// Generated by PeakRDL-regblock-vhdl; record layout translated from the VHDL.
// VHDL package `rxfifo_csr_pkg` stays `rxfifo_csr_pkg` (no name collision).
// VHDL extended type names that contain `.` are rewritten by replacing `.`
// with `_`. Field names and nesting are unchanged, so `isr.rxc.next_q` remains.

`timescale 1ns/1ps

package rxfifo_csr_pkg;

  localparam int unsigned RXFIFO_CSR_DATA_WIDTH = 32;
  localparam int unsigned RXFIFO_CSR_MIN_ADDR_WIDTH = 32;
  localparam int unsigned RXFIFO_CSR_SIZE = 28;

  typedef struct {
    logic next_q;
  } rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_rxc_enable_fe783bbc_in_t;

  typedef struct {
    logic next_q;
  } rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_rwf_enable_b260c2c9_in_t;

  typedef struct {
    logic next_q;
  } rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_rwe_enable_89be3b2a_in_t;

  typedef struct {
    rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_rxc_enable_fe783bbc_in_t rxc;
    rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_rwf_enable_b260c2c9_in_t rwf;
    rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_rwe_enable_89be3b2a_in_t rwe;
  } rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_in_t;

  typedef struct {
    logic [31:0] next_q;
  } rxfifo_csr_fill_usedw_in_t;

  typedef struct {
    rxfifo_csr_fill_usedw_in_t usedw;
  } rxfifo_csr_fill_in_t;

  typedef struct {
    logic [31:0] next_q;
  } rxfifo_csr_length_bytes_in_t;

  typedef struct {
    rxfifo_csr_length_bytes_in_t bytes;
  } rxfifo_csr_length_in_t;

  typedef struct {
    logic [31:0] next_q;
  } rxfifo_csr_read_data_in_t;

  typedef struct {
    rxfifo_csr_read_data_in_t data;
  } rxfifo_csr_read_in_t;

  typedef struct {
    logic [31:0] next_q;
  } rxfifo_csr_src_id_in_t;

  typedef struct {
    rxfifo_csr_src_id_in_t id;
  } rxfifo_csr_src_in_t;

  typedef struct {
    rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_in_t isr;
    rxfifo_csr_fill_in_t                                      fill;
    rxfifo_csr_length_in_t                                    length;
    rxfifo_csr_read_in_t                                      read;
    rxfifo_csr_src_in_t                                       src;
  } rxfifo_csr_in_t;

  typedef struct {
    logic value;
  } rxfifo_csr_ctrl_rst_out_t;

  typedef struct {
    rxfifo_csr_ctrl_rst_out_t rst;
  } rxfifo_csr_ctrl_out_t;

  typedef struct {
    logic intr;
  } rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_out_t;

  typedef struct {
    logic swacc;
  } rxfifo_csr_read_data_out_t;

  typedef struct {
    rxfifo_csr_read_data_out_t data;
  } rxfifo_csr_read_out_t;

  typedef struct {
    rxfifo_csr_ctrl_out_t                                          ctrl;
    rxfifo_csr_isr_rwe_e78eb30e_rwf_7af466c5_rxc_26c7fdd5_out_t     isr;
    rxfifo_csr_read_out_t                                          read;
  } rxfifo_csr_out_t;

endpackage
