// SPDX-FileCopyrightText: 2026 CERN
// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// Modified: 2026-09-25, Kari Vierimaa, Kempele, Finland.
// Translated from VHDL to SystemVerilog.
// Upstream: https://gitlab.com/colibri-cern/colibri commit 3fa784121ccea86d9e65b2e0dc08d2a3327f5f2f

// Generated by PeakRDL-regblock-vhdl; behavior translated from the VHDL.
// The generated `if false` async-reset branch is dead and is omitted.
// `isr.rwe` resets to 1, matching the generated storage reset.

`timescale 1ns/1ps

module rxfifo_csr (
  input  logic        clk,
  input  logic        rst,

  input  logic        s_cpuif_req,
  input  logic        s_cpuif_req_is_wr,
  input  logic [31:0] s_cpuif_addr,
  input  logic [31:0] s_cpuif_wr_data,
  input  logic [31:0] s_cpuif_wr_biten,
  output logic        s_cpuif_req_stall_wr,
  output logic        s_cpuif_req_stall_rd,
  output logic        s_cpuif_rd_ack,
  output logic        s_cpuif_rd_err,
  output logic [31:0] s_cpuif_rd_data,
  output logic        s_cpuif_wr_ack,
  output logic        s_cpuif_wr_err,

  input  rxfifo_csr_pkg::rxfifo_csr_in_t  hwif_in,
  output rxfifo_csr_pkg::rxfifo_csr_out_t hwif_out
);

  logic        cpuif_req;
  logic        cpuif_req_is_wr;
  logic [31:0] cpuif_addr;
  logic [31:0] cpuif_wr_data;
  logic [31:0] cpuif_wr_biten;
  logic        cpuif_req_stall_wr;
  logic        cpuif_req_stall_rd;
  logic        cpuif_rd_ack;
  logic        cpuif_rd_err;
  logic [31:0] cpuif_rd_data;
  logic        cpuif_wr_ack;
  logic        cpuif_wr_err;
  logic        cpuif_req_masked;

  typedef struct {
    logic ctrl;
    logic ier;
    logic isr;
    logic fill;
    logic length;
    logic read;
    logic src;
  } decoded_reg_strb_t;

  decoded_reg_strb_t decoded_reg_strb;
  logic [31:0]       decoded_addr;
  logic              decoded_req;
  logic              decoded_req_is_wr;
  logic [31:0]       decoded_wr_data;
  logic [31:0]       decoded_wr_biten;

  typedef struct {
    logic next_q;
    logic load_next;
  } bit_combo_t;

  typedef struct {
    bit_combo_t rst;
  } ctrl_combo_t;

  typedef struct {
    bit_combo_t rxc;
    bit_combo_t rwf;
    bit_combo_t rwe;
  } trio_combo_t;

  typedef struct {
    ctrl_combo_t ctrl;
    trio_combo_t ier;
    trio_combo_t isr;
  } field_combo_t;

  typedef struct {
    logic value;
  } bit_storage_t;

  typedef struct {
    logic value;
    logic next_q;
  } sticky_storage_t;

  typedef struct {
    bit_storage_t rst;
  } ctrl_storage_t;

  typedef struct {
    bit_storage_t rxc;
    bit_storage_t rwf;
    bit_storage_t rwe;
  } ier_storage_t;

  typedef struct {
    sticky_storage_t rxc;
    sticky_storage_t rwf;
    sticky_storage_t rwe;
  } isr_storage_t;

  typedef struct {
    ctrl_storage_t ctrl;
    ier_storage_t  ier;
    isr_storage_t  isr;
  } field_storage_t;

  field_combo_t   field_combo;
  field_storage_t field_storage;

  logic [31:0] rd_mux_addr;
  logic        readback_err;
  logic        readback_done;
  logic [31:0] readback_data;

  // Leaf clears: Verilator 5.020 emits `struct = 0` for a packed `'0`.
  // rwe resets to 1, matching the VHDL sticky-empty default.
  initial begin
    field_storage.ctrl.rst.value = 1'b0;
    field_storage.ier.rxc.value  = 1'b0;
    field_storage.ier.rwf.value  = 1'b0;
    field_storage.ier.rwe.value  = 1'b0;
    field_storage.isr.rxc.value  = 1'b0;
    field_storage.isr.rxc.next_q = 1'b0;
    field_storage.isr.rwf.value  = 1'b0;
    field_storage.isr.rwf.next_q = 1'b0;
    field_storage.isr.rwe.value  = 1'b1;
    field_storage.isr.rwe.next_q = 1'b1;
  end

  assign cpuif_req            = s_cpuif_req;
  assign cpuif_req_is_wr      = s_cpuif_req_is_wr;
  assign cpuif_addr           = s_cpuif_addr;
  assign cpuif_wr_data        = s_cpuif_wr_data;
  assign cpuif_wr_biten       = s_cpuif_wr_biten;
  assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
  assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
  assign s_cpuif_rd_ack       = cpuif_rd_ack;
  assign s_cpuif_rd_err       = cpuif_rd_err;
  assign s_cpuif_rd_data      = cpuif_rd_data;
  assign s_cpuif_wr_ack       = cpuif_wr_ack;
  assign s_cpuif_wr_err       = cpuif_wr_err;

  assign cpuif_req_stall_rd = 1'b0;
  assign cpuif_req_stall_wr = 1'b0;
  assign cpuif_req_masked   = cpuif_req
    & ~((~cpuif_req_is_wr) & cpuif_req_stall_rd)
    & ~(cpuif_req_is_wr & cpuif_req_stall_wr);

  function automatic logic addr_is(input logic [31:0] addr, input int unsigned value);
    return reg_utils::to_std_logic(reg_utils::regvec#(32)::to_unsigned(addr) == 32'(value));
  endfunction

  always_comb begin : proc_decode
    decoded_reg_strb.ctrl   = cpuif_req_masked & addr_is(cpuif_addr, 32'h0) & cpuif_req_is_wr;
    decoded_reg_strb.ier    = cpuif_req_masked & addr_is(cpuif_addr, 32'h4);
    decoded_reg_strb.isr    = cpuif_req_masked & addr_is(cpuif_addr, 32'h8);
    decoded_reg_strb.fill   = cpuif_req_masked & addr_is(cpuif_addr, 32'hC) & ~cpuif_req_is_wr;
    decoded_reg_strb.length = cpuif_req_masked & addr_is(cpuif_addr, 32'h10) & ~cpuif_req_is_wr;
    decoded_reg_strb.read   = cpuif_req_masked & addr_is(cpuif_addr, 32'h14) & ~cpuif_req_is_wr;
    decoded_reg_strb.src    = cpuif_req_masked & addr_is(cpuif_addr, 32'h18) & ~cpuif_req_is_wr;
  end

  assign decoded_addr      = cpuif_addr;
  assign decoded_req       = cpuif_req_masked;
  assign decoded_req_is_wr = cpuif_req_is_wr;
  assign decoded_wr_data   = cpuif_wr_data;
  assign decoded_wr_biten  = cpuif_wr_biten;

  always_comb begin : proc_field_combo
    logic next_c;
    logic load_next_c;

    next_c      = field_storage.ctrl.rst.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ctrl && decoded_req_is_wr) begin
      next_c      = (field_storage.ctrl.rst.value & ~decoded_wr_biten[0])
                  | (decoded_wr_data[0] & decoded_wr_biten[0]);
      load_next_c = 1'b1;
    end else begin
      next_c      = 1'b0;
      load_next_c = 1'b1;
    end
    field_combo.ctrl.rst.next_q    = next_c;
    field_combo.ctrl.rst.load_next = load_next_c;

    next_c      = field_storage.ier.rxc.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ier && decoded_req_is_wr) begin
      next_c      = (field_storage.ier.rxc.value & ~decoded_wr_biten[0])
                  | (decoded_wr_data[0] & decoded_wr_biten[0]);
      load_next_c = 1'b1;
    end
    field_combo.ier.rxc.next_q    = next_c;
    field_combo.ier.rxc.load_next = load_next_c;

    next_c      = field_storage.ier.rwf.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ier && decoded_req_is_wr) begin
      next_c      = (field_storage.ier.rwf.value & ~decoded_wr_biten[1])
                  | (decoded_wr_data[1] & decoded_wr_biten[1]);
      load_next_c = 1'b1;
    end
    field_combo.ier.rwf.next_q    = next_c;
    field_combo.ier.rwf.load_next = load_next_c;

    next_c      = field_storage.ier.rwe.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ier && decoded_req_is_wr) begin
      next_c      = (field_storage.ier.rwe.value & ~decoded_wr_biten[2])
                  | (decoded_wr_data[2] & decoded_wr_biten[2]);
      load_next_c = 1'b1;
    end
    field_combo.ier.rwe.next_q    = next_c;
    field_combo.ier.rwe.load_next = load_next_c;

    next_c      = field_storage.isr.rxc.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.isr && decoded_req_is_wr) begin
      next_c      = field_storage.isr.rxc.value & ~(decoded_wr_data[0] & decoded_wr_biten[0]);
      load_next_c = 1'b1;
    end else if (reg_utils::or_reduce_sl(~field_storage.isr.rxc.next_q & hwif_in.isr.rxc.next_q)) begin
      next_c      = 1'b1;
      load_next_c = 1'b1;
    end
    field_combo.isr.rxc.next_q    = next_c;
    field_combo.isr.rxc.load_next = load_next_c;

    next_c      = field_storage.isr.rwf.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.isr && decoded_req_is_wr) begin
      next_c      = field_storage.isr.rwf.value & ~(decoded_wr_data[1] & decoded_wr_biten[1]);
      load_next_c = 1'b1;
    end else if (reg_utils::or_reduce_sl(~field_storage.isr.rwf.next_q & hwif_in.isr.rwf.next_q)) begin
      next_c      = 1'b1;
      load_next_c = 1'b1;
    end
    field_combo.isr.rwf.next_q    = next_c;
    field_combo.isr.rwf.load_next = load_next_c;

    next_c      = field_storage.isr.rwe.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.isr && decoded_req_is_wr) begin
      next_c      = field_storage.isr.rwe.value & ~(decoded_wr_data[2] & decoded_wr_biten[2]);
      load_next_c = 1'b1;
    end else if (reg_utils::or_reduce_sl(~field_storage.isr.rwe.next_q & hwif_in.isr.rwe.next_q)) begin
      next_c      = 1'b1;
      load_next_c = 1'b1;
    end
    field_combo.isr.rwe.next_q    = next_c;
    field_combo.isr.rwe.load_next = load_next_c;
  end

  always_ff @(posedge clk) begin : proc_field_storage
    if (rst) begin
      field_storage.ctrl.rst.value <= 1'b0;
      field_storage.ier.rxc.value  <= 1'b0;
      field_storage.ier.rwf.value  <= 1'b0;
      field_storage.ier.rwe.value  <= 1'b0;
      field_storage.isr.rxc.value  <= 1'b0;
      field_storage.isr.rxc.next_q <= 1'b0;
      field_storage.isr.rwf.value  <= 1'b0;
      field_storage.isr.rwf.next_q <= 1'b0;
      field_storage.isr.rwe.value  <= 1'b1;
      field_storage.isr.rwe.next_q <= 1'b1;
    end else begin
      if (field_combo.ctrl.rst.load_next)
        field_storage.ctrl.rst.value <= field_combo.ctrl.rst.next_q;
      if (field_combo.ier.rxc.load_next)
        field_storage.ier.rxc.value <= field_combo.ier.rxc.next_q;
      if (field_combo.ier.rwf.load_next)
        field_storage.ier.rwf.value <= field_combo.ier.rwf.next_q;
      if (field_combo.ier.rwe.load_next)
        field_storage.ier.rwe.value <= field_combo.ier.rwe.next_q;
      if (field_combo.isr.rxc.load_next)
        field_storage.isr.rxc.value <= field_combo.isr.rxc.next_q;
      field_storage.isr.rxc.next_q <= hwif_in.isr.rxc.next_q;
      if (field_combo.isr.rwf.load_next)
        field_storage.isr.rwf.value <= field_combo.isr.rwf.next_q;
      field_storage.isr.rwf.next_q <= hwif_in.isr.rwf.next_q;
      if (field_combo.isr.rwe.load_next)
        field_storage.isr.rwe.value <= field_combo.isr.rwe.next_q;
      field_storage.isr.rwe.next_q <= hwif_in.isr.rwe.next_q;
    end
  end

  always_comb begin : proc_hwif_out
    hwif_out.ctrl.rst.value = field_storage.ctrl.rst.value;
    hwif_out.isr.intr       = (field_storage.isr.rxc.value & field_storage.ier.rxc.value)
                            | (field_storage.isr.rwf.value & field_storage.ier.rwf.value)
                            | (field_storage.isr.rwe.value & field_storage.ier.rwe.value);
    hwif_out.read.data.swacc = decoded_reg_strb.read;
  end

  assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
  assign cpuif_wr_err = 1'b0;

  assign rd_mux_addr = decoded_addr;

  always_comb begin : proc_readback
    logic [31:0] readback_data_var;
    readback_data_var = '0;
    if (rd_mux_addr == 32'h4) begin
      readback_data_var[0] = field_storage.ier.rxc.value;
      readback_data_var[1] = field_storage.ier.rwf.value;
      readback_data_var[2] = field_storage.ier.rwe.value;
    end
    if (rd_mux_addr == 32'h8) begin
      readback_data_var[0] = field_storage.isr.rxc.value;
      readback_data_var[1] = field_storage.isr.rwf.value;
      readback_data_var[2] = field_storage.isr.rwe.value;
    end
    if (rd_mux_addr == 32'hC)
      readback_data_var = hwif_in.fill.usedw.next_q;
    if (rd_mux_addr == 32'h10)
      readback_data_var = hwif_in.length.bytes.next_q;
    if (rd_mux_addr == 32'h14)
      readback_data_var = hwif_in.read.data.next_q;
    if (rd_mux_addr == 32'h18)
      readback_data_var = hwif_in.src.id.next_q;
    readback_data = readback_data_var;
    readback_done = decoded_req & ~decoded_req_is_wr;
    readback_err  = 1'b0;
  end

  assign cpuif_rd_ack  = readback_done;
  assign cpuif_rd_data = readback_data;
  assign cpuif_rd_err  = readback_err;

endmodule
