// SPDX-FileCopyrightText: 2026 CERN
// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// Modified: 2026-09-25, Kari Vierimaa, Kempele, Finland.
// Translated from VHDL to SystemVerilog.
// Upstream: https://gitlab.com/colibri-cern/colibri commit 3fa784121ccea86d9e65b2e0dc08d2a3327f5f2f

// Generated by PeakRDL-regblock-vhdl; behavior translated from the VHDL.
// The generated `if false` async-reset branch is dead and is omitted.
// Field storage flops are one clocked process; each field still updates on
// its own `load_next`, and sticky `next_q` samples every cycle.

`timescale 1ns/1ps

module txfifo_csr (
  input  logic        clk,
  input  logic        rst,

  input  logic        s_cpuif_req,
  input  logic        s_cpuif_req_is_wr,
  input  logic [31:0] s_cpuif_addr,
  input  logic [31:0] s_cpuif_wr_data,
  input  logic [31:0] s_cpuif_wr_biten,
  output logic        s_cpuif_req_stall_wr,
  output logic        s_cpuif_req_stall_rd,
  output logic        s_cpuif_rd_ack,
  output logic        s_cpuif_rd_err,
  output logic [31:0] s_cpuif_rd_data,
  output logic        s_cpuif_wr_ack,
  output logic        s_cpuif_wr_err,

  input  txfifo_csr_pkg::txfifo_csr_in_t  hwif_in,
  output txfifo_csr_pkg::txfifo_csr_out_t hwif_out
);

  logic        cpuif_req;
  logic        cpuif_req_is_wr;
  logic [31:0] cpuif_addr;
  logic [31:0] cpuif_wr_data;
  logic [31:0] cpuif_wr_biten;
  logic        cpuif_req_stall_wr;
  logic        cpuif_req_stall_rd;
  logic        cpuif_rd_ack;
  logic        cpuif_rd_err;
  logic [31:0] cpuif_rd_data;
  logic        cpuif_wr_ack;
  logic        cpuif_wr_err;
  logic        cpuif_req_masked;

  typedef struct {
    logic ctrl;
    logic ier;
    logic isr;
    logic fill;
    logic length;
    logic write;
    logic dst;
  } decoded_reg_strb_t;

  decoded_reg_strb_t decoded_reg_strb;
  logic [31:0]       decoded_addr;
  logic              decoded_req;
  logic              decoded_req_is_wr;
  logic [31:0]       decoded_wr_data;
  logic [31:0]       decoded_wr_biten;

  typedef struct {
    logic next_q;
    logic load_next;
  } bit_combo_t;

  typedef struct {
    logic [31:0] next_q;
    logic        load_next;
  } word_combo_t;

  typedef struct {
    bit_combo_t  rst;
    bit_combo_t  flush;
  } ctrl_combo_t;

  typedef struct {
    bit_combo_t txc;
    bit_combo_t wrf;
    bit_combo_t tle;
  } trio_combo_t;

  typedef struct {
    word_combo_t bytes;
  } length_combo_t;

  typedef struct {
    word_combo_t data;
  } write_combo_t;

  typedef struct {
    word_combo_t id;
  } dst_combo_t;

  typedef struct {
    ctrl_combo_t   ctrl;
    trio_combo_t   ier;
    trio_combo_t   isr;
    length_combo_t length;
    write_combo_t  write;
    dst_combo_t    dst;
  } field_combo_t;

  typedef struct {
    logic value;
  } bit_storage_t;

  typedef struct {
    logic value;
    logic next_q;
  } sticky_storage_t;

  typedef struct {
    bit_storage_t rst;
    bit_storage_t flush;
  } ctrl_storage_t;

  typedef struct {
    bit_storage_t txc;
    bit_storage_t wrf;
    bit_storage_t tle;
  } ier_storage_t;

  typedef struct {
    sticky_storage_t txc;
    sticky_storage_t wrf;
    sticky_storage_t tle;
  } isr_storage_t;

  typedef struct {
    logic [31:0] value;
  } word_storage_t;

  typedef struct {
    word_storage_t bytes;
  } length_storage_t;

  typedef struct {
    word_storage_t data;
  } write_storage_t;

  typedef struct {
    word_storage_t id;
  } dst_storage_t;

  typedef struct {
    ctrl_storage_t   ctrl;
    ier_storage_t    ier;
    isr_storage_t    isr;
    length_storage_t length;
    write_storage_t  write;
    dst_storage_t    dst;
  } field_storage_t;

  field_combo_t   field_combo;
  field_storage_t field_storage;

  logic [31:0] rd_mux_addr;
  logic        readback_err;
  logic        readback_done;
  logic [31:0] readback_data;

  // Leaf clears: Verilator 5.020 emits `struct = 0` for a packed `'0`,
  // which does not compile for this nested storage record.
  initial begin
    field_storage.ctrl.rst.value     = 1'b0;
    field_storage.ctrl.flush.value   = 1'b0;
    field_storage.ier.txc.value      = 1'b0;
    field_storage.ier.wrf.value      = 1'b0;
    field_storage.ier.tle.value      = 1'b0;
    field_storage.isr.txc.value      = 1'b0;
    field_storage.isr.txc.next_q     = 1'b0;
    field_storage.isr.wrf.value      = 1'b0;
    field_storage.isr.wrf.next_q     = 1'b0;
    field_storage.isr.tle.value      = 1'b0;
    field_storage.isr.tle.next_q     = 1'b0;
    field_storage.length.bytes.value = '0;
    field_storage.write.data.value   = '0;
    field_storage.dst.id.value       = '0;
  end

  assign cpuif_req            = s_cpuif_req;
  assign cpuif_req_is_wr      = s_cpuif_req_is_wr;
  assign cpuif_addr           = s_cpuif_addr;
  assign cpuif_wr_data        = s_cpuif_wr_data;
  assign cpuif_wr_biten       = s_cpuif_wr_biten;
  assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
  assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
  assign s_cpuif_rd_ack       = cpuif_rd_ack;
  assign s_cpuif_rd_err       = cpuif_rd_err;
  assign s_cpuif_rd_data      = cpuif_rd_data;
  assign s_cpuif_wr_ack       = cpuif_wr_ack;
  assign s_cpuif_wr_err       = cpuif_wr_err;

  assign cpuif_req_stall_rd = 1'b0;
  assign cpuif_req_stall_wr = 1'b0;
  assign cpuif_req_masked   = cpuif_req
    & ~((~cpuif_req_is_wr) & cpuif_req_stall_rd)
    & ~(cpuif_req_is_wr & cpuif_req_stall_wr);

  function automatic logic addr_is(input logic [31:0] addr, input int unsigned value);
    return reg_utils::to_std_logic(reg_utils::regvec#(32)::to_unsigned(addr) == 32'(value));
  endfunction

  always_comb begin : proc_decode
    decoded_reg_strb.ctrl   = cpuif_req_masked & addr_is(cpuif_addr, 32'h0) & cpuif_req_is_wr;
    decoded_reg_strb.ier    = cpuif_req_masked & addr_is(cpuif_addr, 32'h4);
    decoded_reg_strb.isr    = cpuif_req_masked & addr_is(cpuif_addr, 32'h8);
    decoded_reg_strb.fill   = cpuif_req_masked & addr_is(cpuif_addr, 32'hC) & ~cpuif_req_is_wr;
    decoded_reg_strb.length = cpuif_req_masked & addr_is(cpuif_addr, 32'h10);
    decoded_reg_strb.write  = cpuif_req_masked & addr_is(cpuif_addr, 32'h14) & cpuif_req_is_wr;
    decoded_reg_strb.dst    = cpuif_req_masked & addr_is(cpuif_addr, 32'h18);
  end

  assign decoded_addr      = cpuif_addr;
  assign decoded_req       = cpuif_req_masked;
  assign decoded_req_is_wr = cpuif_req_is_wr;
  assign decoded_wr_data   = cpuif_wr_data;
  assign decoded_wr_biten  = cpuif_wr_biten;

  always_comb begin : proc_field_combo
    logic        next_c;
    logic        load_next_c;
    logic [31:0] next_w;
    logic        load_next_w;

    // ctrl.rst, singlepulse, bit 0
    next_c      = field_storage.ctrl.rst.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ctrl && decoded_req_is_wr) begin
      next_c      = (field_storage.ctrl.rst.value & ~decoded_wr_biten[0])
                  | (decoded_wr_data[0] & decoded_wr_biten[0]);
      load_next_c = 1'b1;
    end else begin
      next_c      = 1'b0;
      load_next_c = 1'b1;
    end
    field_combo.ctrl.rst.next_q    = next_c;
    field_combo.ctrl.rst.load_next = load_next_c;

    // ctrl.flush, singlepulse, bit 1
    next_c      = field_storage.ctrl.flush.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ctrl && decoded_req_is_wr) begin
      next_c      = (field_storage.ctrl.flush.value & ~decoded_wr_biten[1])
                  | (decoded_wr_data[1] & decoded_wr_biten[1]);
      load_next_c = 1'b1;
    end else begin
      next_c      = 1'b0;
      load_next_c = 1'b1;
    end
    field_combo.ctrl.flush.next_q    = next_c;
    field_combo.ctrl.flush.load_next = load_next_c;

    // ier.txc bit 0
    next_c      = field_storage.ier.txc.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ier && decoded_req_is_wr) begin
      next_c      = (field_storage.ier.txc.value & ~decoded_wr_biten[0])
                  | (decoded_wr_data[0] & decoded_wr_biten[0]);
      load_next_c = 1'b1;
    end
    field_combo.ier.txc.next_q    = next_c;
    field_combo.ier.txc.load_next = load_next_c;

    // ier.wrf bit 1
    next_c      = field_storage.ier.wrf.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ier && decoded_req_is_wr) begin
      next_c      = (field_storage.ier.wrf.value & ~decoded_wr_biten[1])
                  | (decoded_wr_data[1] & decoded_wr_biten[1]);
      load_next_c = 1'b1;
    end
    field_combo.ier.wrf.next_q    = next_c;
    field_combo.ier.wrf.load_next = load_next_c;

    // ier.tle bit 2
    next_c      = field_storage.ier.tle.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.ier && decoded_req_is_wr) begin
      next_c      = (field_storage.ier.tle.value & ~decoded_wr_biten[2])
                  | (decoded_wr_data[2] & decoded_wr_biten[2]);
      load_next_c = 1'b1;
    end
    field_combo.ier.tle.next_q    = next_c;
    field_combo.ier.tle.load_next = load_next_c;

    // isr.txc write-1-to-clear, posedge sticky
    next_c      = field_storage.isr.txc.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.isr && decoded_req_is_wr) begin
      next_c      = field_storage.isr.txc.value & ~(decoded_wr_data[0] & decoded_wr_biten[0]);
      load_next_c = 1'b1;
    end else if (reg_utils::or_reduce_sl(~field_storage.isr.txc.next_q & hwif_in.isr.txc.next_q)) begin
      next_c      = 1'b1;
      load_next_c = 1'b1;
    end
    field_combo.isr.txc.next_q    = next_c;
    field_combo.isr.txc.load_next = load_next_c;

    // isr.wrf
    next_c      = field_storage.isr.wrf.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.isr && decoded_req_is_wr) begin
      next_c      = field_storage.isr.wrf.value & ~(decoded_wr_data[1] & decoded_wr_biten[1]);
      load_next_c = 1'b1;
    end else if (reg_utils::or_reduce_sl(~field_storage.isr.wrf.next_q & hwif_in.isr.wrf.next_q)) begin
      next_c      = 1'b1;
      load_next_c = 1'b1;
    end
    field_combo.isr.wrf.next_q    = next_c;
    field_combo.isr.wrf.load_next = load_next_c;

    // isr.tle
    next_c      = field_storage.isr.tle.value;
    load_next_c = 1'b0;
    if (decoded_reg_strb.isr && decoded_req_is_wr) begin
      next_c      = field_storage.isr.tle.value & ~(decoded_wr_data[2] & decoded_wr_biten[2]);
      load_next_c = 1'b1;
    end else if (reg_utils::or_reduce_sl(~field_storage.isr.tle.next_q & hwif_in.isr.tle.next_q)) begin
      next_c      = 1'b1;
      load_next_c = 1'b1;
    end
    field_combo.isr.tle.next_q    = next_c;
    field_combo.isr.tle.load_next = load_next_c;

    // length.bytes
    next_w      = field_storage.length.bytes.value;
    load_next_w = 1'b0;
    if (decoded_reg_strb.length && decoded_req_is_wr) begin
      next_w      = (field_storage.length.bytes.value & ~decoded_wr_biten)
                  | (decoded_wr_data & decoded_wr_biten);
      load_next_w = 1'b1;
    end
    field_combo.length.bytes.next_q    = next_w;
    field_combo.length.bytes.load_next = load_next_w;

    // write.data
    next_w      = field_storage.write.data.value;
    load_next_w = 1'b0;
    if (decoded_reg_strb.write && decoded_req_is_wr) begin
      next_w      = (field_storage.write.data.value & ~decoded_wr_biten)
                  | (decoded_wr_data & decoded_wr_biten);
      load_next_w = 1'b1;
    end
    field_combo.write.data.next_q    = next_w;
    field_combo.write.data.load_next = load_next_w;

    // dst.id
    next_w      = field_storage.dst.id.value;
    load_next_w = 1'b0;
    if (decoded_reg_strb.dst && decoded_req_is_wr) begin
      next_w      = (field_storage.dst.id.value & ~decoded_wr_biten)
                  | (decoded_wr_data & decoded_wr_biten);
      load_next_w = 1'b1;
    end
    field_combo.dst.id.next_q    = next_w;
    field_combo.dst.id.load_next = load_next_w;
  end

  always_ff @(posedge clk) begin : proc_field_storage
    if (rst) begin
      field_storage.ctrl.rst.value     <= 1'b0;
      field_storage.ctrl.flush.value   <= 1'b0;
      field_storage.ier.txc.value      <= 1'b0;
      field_storage.ier.wrf.value      <= 1'b0;
      field_storage.ier.tle.value      <= 1'b0;
      field_storage.isr.txc.value      <= 1'b0;
      field_storage.isr.txc.next_q     <= 1'b0;
      field_storage.isr.wrf.value      <= 1'b0;
      field_storage.isr.wrf.next_q     <= 1'b0;
      field_storage.isr.tle.value      <= 1'b0;
      field_storage.isr.tle.next_q     <= 1'b0;
      field_storage.length.bytes.value <= '0;
      field_storage.write.data.value   <= '0;
      field_storage.dst.id.value       <= '0;
    end else begin
      if (field_combo.ctrl.rst.load_next)
        field_storage.ctrl.rst.value <= field_combo.ctrl.rst.next_q;
      if (field_combo.ctrl.flush.load_next)
        field_storage.ctrl.flush.value <= field_combo.ctrl.flush.next_q;
      if (field_combo.ier.txc.load_next)
        field_storage.ier.txc.value <= field_combo.ier.txc.next_q;
      if (field_combo.ier.wrf.load_next)
        field_storage.ier.wrf.value <= field_combo.ier.wrf.next_q;
      if (field_combo.ier.tle.load_next)
        field_storage.ier.tle.value <= field_combo.ier.tle.next_q;
      if (field_combo.isr.txc.load_next)
        field_storage.isr.txc.value <= field_combo.isr.txc.next_q;
      field_storage.isr.txc.next_q <= hwif_in.isr.txc.next_q;
      if (field_combo.isr.wrf.load_next)
        field_storage.isr.wrf.value <= field_combo.isr.wrf.next_q;
      field_storage.isr.wrf.next_q <= hwif_in.isr.wrf.next_q;
      if (field_combo.isr.tle.load_next)
        field_storage.isr.tle.value <= field_combo.isr.tle.next_q;
      field_storage.isr.tle.next_q <= hwif_in.isr.tle.next_q;
      if (field_combo.length.bytes.load_next)
        field_storage.length.bytes.value <= field_combo.length.bytes.next_q;
      if (field_combo.write.data.load_next)
        field_storage.write.data.value <= field_combo.write.data.next_q;
      if (field_combo.dst.id.load_next)
        field_storage.dst.id.value <= field_combo.dst.id.next_q;
    end
  end

  always_comb begin : proc_hwif_out
    hwif_out.ctrl.rst.value      = field_storage.ctrl.rst.value;
    hwif_out.ctrl.flush.value    = field_storage.ctrl.flush.value;
    hwif_out.isr.intr            = (field_storage.isr.txc.value & field_storage.ier.txc.value)
                                 | (field_storage.isr.wrf.value & field_storage.ier.wrf.value)
                                 | (field_storage.isr.tle.value & field_storage.ier.tle.value);
    hwif_out.length.bytes.value  = field_storage.length.bytes.value;
    hwif_out.length.bytes.swmod  = decoded_reg_strb.length & decoded_req_is_wr
                                 & reg_utils::regvec#(32)::or_reduce(decoded_wr_biten);
    hwif_out.write.data.value    = field_storage.write.data.value;
    hwif_out.write.data.swmod    = decoded_reg_strb.write & decoded_req_is_wr
                                 & reg_utils::regvec#(32)::or_reduce(decoded_wr_biten);
    hwif_out.dst.id.value        = field_storage.dst.id.value;
  end

  assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
  assign cpuif_wr_err = 1'b0;

  assign rd_mux_addr = decoded_addr;

  always_comb begin : proc_readback
    logic [31:0] readback_data_var;
    readback_data_var = '0;
    if (rd_mux_addr == 32'h4) begin
      readback_data_var[0] = field_storage.ier.txc.value;
      readback_data_var[1] = field_storage.ier.wrf.value;
      readback_data_var[2] = field_storage.ier.tle.value;
    end
    if (rd_mux_addr == 32'h8) begin
      readback_data_var[0] = field_storage.isr.txc.value;
      readback_data_var[1] = field_storage.isr.wrf.value;
      readback_data_var[2] = field_storage.isr.tle.value;
    end
    if (rd_mux_addr == 32'hC)
      readback_data_var = hwif_in.fill.usedw.next_q;
    if (rd_mux_addr == 32'h10)
      readback_data_var = field_storage.length.bytes.value;
    if (rd_mux_addr == 32'h18)
      readback_data_var = field_storage.dst.id.value;
    readback_data = readback_data_var;
    readback_done = decoded_req & ~decoded_req_is_wr;
    readback_err  = 1'b0;
  end

  assign cpuif_rd_ack  = readback_done;
  assign cpuif_rd_data = readback_data;
  assign cpuif_rd_err  = readback_err;

endmodule
