// SPDX-FileCopyrightText: 2026 CERN
// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// Modified: 2026-09-25, Kari Vierimaa, Kempele, Finland.
// Translated from VHDL to SystemVerilog.
// Upstream: https://gitlab.com/colibri-cern/colibri commit 3fa784121ccea86d9e65b2e0dc08d2a3327f5f2f

// Generated by PeakRDL-regblock-vhdl; record layout translated from the VHDL.
// VHDL package `txfifo_csr_pkg` stays `txfifo_csr_pkg` (no name collision).
// VHDL extended type names that contain `.` are rewritten by replacing `.`
// with `_`. Field names and nesting are unchanged, so `isr.txc.next_q` remains.

`timescale 1ns/1ps

package txfifo_csr_pkg;

  localparam int unsigned TXFIFO_CSR_DATA_WIDTH = 32;
  localparam int unsigned TXFIFO_CSR_MIN_ADDR_WIDTH = 32;
  localparam int unsigned TXFIFO_CSR_SIZE = 28;

  // \txfifo_csr.isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5.txc_enable_2b3d05ec_in_t\
  typedef struct {
    logic next_q;
  } txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_txc_enable_2b3d05ec_in_t;

  typedef struct {
    logic next_q;
  } txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_wrf_enable_fd73e106_in_t;

  typedef struct {
    logic next_q;
  } txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_tle_enable_47109f76_in_t;

  typedef struct {
    txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_txc_enable_2b3d05ec_in_t txc;
    txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_wrf_enable_fd73e106_in_t wrf;
    txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_tle_enable_47109f76_in_t tle;
  } txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_in_t;

  typedef struct {
    logic [31:0] next_q;
  } txfifo_csr_fill_usedw_in_t;

  typedef struct {
    txfifo_csr_fill_usedw_in_t usedw;
  } txfifo_csr_fill_in_t;

  typedef struct {
    txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_in_t isr;
    txfifo_csr_fill_in_t                                      fill;
  } txfifo_csr_in_t;

  typedef struct {
    logic value;
  } txfifo_csr_ctrl_rst_out_t;

  typedef struct {
    logic value;
  } txfifo_csr_ctrl_flush_out_t;

  typedef struct {
    txfifo_csr_ctrl_rst_out_t   rst;
    txfifo_csr_ctrl_flush_out_t flush;
  } txfifo_csr_ctrl_out_t;

  typedef struct {
    logic intr;
  } txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_out_t;

  typedef struct {
    logic [31:0] value;
    logic        swmod;
  } txfifo_csr_length_bytes_out_t;

  typedef struct {
    txfifo_csr_length_bytes_out_t bytes;
  } txfifo_csr_length_out_t;

  typedef struct {
    logic [31:0] value;
    logic        swmod;
  } txfifo_csr_write_data_out_t;

  typedef struct {
    txfifo_csr_write_data_out_t data;
  } txfifo_csr_write_out_t;

  typedef struct {
    logic [31:0] value;
  } txfifo_csr_dst_id_out_t;

  typedef struct {
    txfifo_csr_dst_id_out_t id;
  } txfifo_csr_dst_out_t;

  typedef struct {
    txfifo_csr_ctrl_out_t                                          ctrl;
    txfifo_csr_isr_tle_a35f8835_txc_8bc4763f_wrf_031446d5_out_t     isr;
    txfifo_csr_length_out_t                                        length;
    txfifo_csr_write_out_t                                         write;
    txfifo_csr_dst_out_t                                           dst;
  } txfifo_csr_out_t;

endpackage
