#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
#
# Ancillary repository file (not Covered Source). RTL is under CERN-OHL-W; see NOTICE.

"""Regenerate colibri.f, Bender.yml, and colibri.core from verilator file lists.

Run from anywhere:

    python tools/gen_packaging.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

FRAGMENTS = [
    "verilator/colibri.f",
    "verilator/files/common.f",
    "verilator/files/memory.f",
    "verilator/files/comms.f",
    "verilator/files/endec.f",
    "verilator/files/io.f",
    "verilator/files/interfaces.f",
    "verilator/files/misc.f",
    "verilator/files/packet_pipes.f",
    "verilator/files/aurora.f",
    "verilator/files/fileio.f",
]


def rtl_files() -> list[str]:
    files: list[str] = []
    seen: set[str] = set()
    for rel in FRAGMENTS:
        for line in (ROOT / rel).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("src/") and line.endswith(".sv") and line not in seen:
                seen.add(line)
                files.append(line)
    all_sv = sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / "src").rglob("*.sv"))
    if set(files) != set(all_sv):
        missing = sorted(set(all_sv) - set(files))
        extra = sorted(set(files) - set(all_sv))
        raise SystemExit(f"RTL list mismatch missing={missing} extra={extra}")
    return files


def sim_files() -> list[str]:
    sims = sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / "sim").rglob("*.sv"))
    pkg = "sim/packet/packet_tb_pkg.sv"
    if pkg in sims:
        sims.remove(pkg)
        idx = next(i for i, name in enumerate(sims) if name.startswith("sim/packet/"))
        sims.insert(idx, pkg)
    return sims


def write_colibri_f(rtl: list[str]) -> None:
    header = """// SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland
//
// Ancillary repository file (not Covered Source). RTL is under CERN-OHL-W; see NOTICE.

// Complete Colibri SystemVerilog RTL file list (dependency order).
// Run from the colibri_sv directory, for example:
//   verilator --lint-only -Wall -Wno-DECLFILENAME -Wno-MULTITOP -f colibri.f
//
// Order matches verilator/files/*.f (see docs/playbooks/simulation.md).
// Regenerated by tools/gen_packaging.py. Verilator regression still uses
// verilator/colibri.f plus per-domain lists.

+incdir+src
"""
    (ROOT / "colibri.f").write_text(header + "\n".join(rtl) + "\n", encoding="utf-8", newline="\n")


def write_bender(rtl: list[str]) -> None:
    lines = [
        "# SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland",
        "#",
        "# Ancillary repository file (not Covered Source). RTL is under CERN-OHL-W; see NOTICE.",
        "# Regenerated by tools/gen_packaging.py.",
        "",
        "package:",
        "  name: colibri-sv",
        "  authors:",
        '    - "Kari Vierimaa"',
        "  version: 0.1.0",
        "  description: SystemVerilog port of CERN colibri for Verilator and FPGA/ASIC flows",
        "",
        "dependencies: {}",
        "",
        "export_include_dirs:",
        "  - src",
        "",
        "sources:",
    ]
    lines.extend(f"  - {path}" for path in rtl)
    (ROOT / "Bender.yml").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def write_core(rtl: list[str], sim: list[str]) -> None:
    lines = [
        "CAPI=2:",
        "",
        "# SPDX-FileCopyrightText: 2026 Kari Vierimaa, Kempele, Finland",
        "#",
        "# Ancillary repository file (not Covered Source). RTL is under CERN-OHL-W; see NOTICE.",
        "# Regenerated by tools/gen_packaging.py.",
        "",
        "name: kavierim:colibri:sv:0.1.0",
        "description: SystemVerilog port of CERN colibri (Verilator-oriented RTL library)",
        "",
        "filesets:",
        "  rtl:",
        "    files:",
    ]
    lines.extend(f"      - {path}" for path in rtl)
    lines.extend(
        [
            "    file_type: systemVerilogSource",
            "  sim:",
            "    files:",
        ]
    )
    lines.extend(f"      - {path}" for path in sim)
    lines.extend(
        [
            "    file_type: systemVerilogSource",
            "",
            "targets:",
            "  default:",
            "    filesets:",
            "      - rtl",
            "    tools:",
            "      verilator:",
            "        verilator_options:",
            "          - -Isrc",
            "  sim:",
            "    filesets:",
            "      - rtl",
            "      - sim",
            "    default_tool: verilator",
            "    parameters:",
            "      top_module:",
            "        datatype: str",
            "        default: counter_tb",
            "        description: Testbench module elaborated by this run (one of sim/**/*_tb.sv)",
            '    toplevel: ["${top_module}"]',
            "    tools:",
            "      verilator:",
            "        mode: binary",
            "        verilator_options:",
            "          - --timing",
            "          - --assert",
            "          - -Isrc",
            "          - -Wno-DECLFILENAME",
            "          - -Wno-MULTITOP",
            "",
        ]
    )
    (ROOT / "colibri.core").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    rtl = rtl_files()
    sim = sim_files()
    write_colibri_f(rtl)
    write_bender(rtl)
    write_core(rtl, sim)
    print(f"Wrote colibri.f ({len(rtl)} RTL), Bender.yml, colibri.core ({len(sim)} sim files)")


if __name__ == "__main__":
    main()
